const state = { token: sessionStorage.getItem('learning_access_token') || '', refreshToken: sessionStorage.getItem('learning_refresh_token') || '', refreshing: null, user: null, courses: [], questions: [], practice: null, agentSessionId: Number(localStorage.getItem('learning_agent_session_id')) || null, agentSessions: [] };
const $ = selector => document.querySelector(selector);
const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
function flash(message) { const root = $('#flash'); root.textContent = message; root.classList.remove('hidden'); setTimeout(() => root.classList.add('hidden'), 2800); }
function storeTokens(tokens) { state.token = tokens.access_token; state.refreshToken = tokens.refresh_token; sessionStorage.setItem('learning_access_token', state.token); sessionStorage.setItem('learning_refresh_token', state.refreshToken); }
async function refreshAccessToken() { if (!state.refreshToken) throw new Error('Session expired'); if (!state.refreshing) state.refreshing = fetch('/v1/auth/refresh', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ refresh_token: state.refreshToken }) }).then(async response => { if (!response.ok) throw new Error('Session expired'); return response.json(); }).then(storeTokens).finally(() => { state.refreshing = null; }); return state.refreshing; }
async function api(path, options = {}, retried = false) { const headers = { ...(options.headers || {}) }; if (state.token) headers.Authorization = `Bearer ${state.token}`; if (options.body && !(options.body instanceof FormData)) headers['Content-Type'] = 'application/json'; const response = await fetch(`/v1${path}`, { ...options, headers }); if (response.status === 401 && !retried && path !== '/auth/refresh') { try { await refreshAccessToken(); return api(path, options, true); } catch (error) { showAuth(); throw error; } } if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.detail || 'Request failed'); } return response.status === 204 ? null : response.json(); }
function courseOptions(emptyLabel = 'No course') { return `<option value="">${emptyLabel}</option>${state.courses.map(course => `<option value="${course.id}">${escapeHtml(course.name)}</option>`).join('')}`; }
async function ensureCourses() { if (!state.courses.length) state.courses = await api('/courses'); }
function showAuth() { state.token = ''; state.refreshToken = ''; state.user = null; sessionStorage.removeItem('learning_access_token'); sessionStorage.removeItem('learning_refresh_token'); $('#app-view').classList.add('hidden'); $('#auth-view').classList.remove('hidden'); }
function showApp() { $('#auth-view').classList.add('hidden'); $('#app-view').classList.remove('hidden'); $('#user-label').textContent = state.user.display_name || state.user.email; $('#org-label').textContent = `${state.user.tenant_id.slice(0, 8)} · ${state.user.role}`; loadCurrentView(); }
async function authenticate(path, form) { const tokens = await api(path, { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(form))) }); storeTokens(tokens); state.user = await api('/me'); showApp(); }

document.querySelectorAll('[data-auth-tab]').forEach(button => button.onclick = () => { document.querySelectorAll('[data-auth-tab]').forEach(item => item.classList.toggle('active', item === button)); $('#login-form').classList.toggle('hidden', button.dataset.authTab !== 'login'); $('#register-form').classList.toggle('hidden', button.dataset.authTab !== 'register'); $('#auth-error').textContent = ''; });
$('#login-form').onsubmit = async event => { event.preventDefault(); try { await authenticate('/auth/login', event.target); } catch (error) { $('#auth-error').textContent = error.message; } };
$('#register-form').onsubmit = async event => { event.preventDefault(); try { await authenticate('/auth/register', event.target); } catch (error) { $('#auth-error').textContent = error.message; } };
document.querySelectorAll('.sidebar .nav-item[data-view]').forEach(button => button.onclick = () => openView(button.dataset.view));
function openView(view) { const target = $(`#${view}-view`); if (!target) return; document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.view === view)); document.querySelectorAll('.view').forEach(item => item.classList.add('hidden')); target.classList.remove('hidden'); $('#view-title').textContent = ({ dashboard: 'Overview', courses: 'Courses', tasks: 'Tasks', goals: 'Goals & knowledge', practice: 'Practice & review', vocabulary: 'Vocabulary', resources: 'Resources & RAG', ai: 'Learning Agent', members: 'Team' })[view] || 'Learning Space'; void loadCurrentView(view); }
async function loadCurrentView(activeView) { const view = activeView || document.querySelector('.sidebar .nav-item.active')?.dataset.view; const loads = { dashboard: loadDashboard, courses: loadCourses, tasks: loadTasks, goals: loadGoals, practice: loadPractice, vocabulary: loadVocabulary, resources: loadResources, ai: loadAiCenter, members: loadMembers }; const load = loads[view]; if (typeof load === 'function') await load(); }
async function loadVocabulary() { try { const [all, due] = await Promise.all([api('/vocabulary'), api('/vocabulary?due_only=true')]); const row = item => `<article class="list-row"><div><strong>${escapeHtml(item.word)}</strong><div class="task-meta">${escapeHtml(item.meaning)} · next ${item.next_review}</div>${item.example ? `<div>${escapeHtml(item.example)}</div>` : ''}</div><span class="task-meta">streak ${item.streak}</span></article>`; $('#vocabulary-list').innerHTML = all.map(row).join('') || '<span class="task-meta">No words yet.</span>'; $('#vocabulary-due').innerHTML = due.map(row).join('') || '<span class="task-meta">Nothing due today.</span>'; } catch (error) { flash(error.message); } }

function taskRow(task) { return `<article class="list-row"><div><strong>${escapeHtml(task.title)}</strong><div class="task-meta">${task.planned_date} · ${task.duration_minutes} min${task.scheduled_time ? ` · reminder ${task.scheduled_time}` : ''}</div></div>${task.completed ? '<span class="complete">Completed</span>' : `<button class="secondary" data-complete="${task.id}">Complete</button>`}</article>`; }
async function loadDashboard() { try { const data = await api('/dashboard'); const metrics = [['Study time', `${data.study_minutes} min`], ['Tasks', `${data.tasks.completed}/${data.tasks.total}`], ['Practice accuracy', `${data.practice.accuracy}%`], ['Due reviews', data.reviews.due]]; $('#metrics').innerHTML = metrics.map(([label, value]) => `<article class="metric"><div class="label">${label}</div><div class="value">${value}</div></article>`).join(''); const tasks = await api('/tasks'); const today = new Date().toISOString().slice(0, 10); $('#today-tasks').innerHTML = tasks.filter(task => task.planned_date === today).slice(0, 6).map(taskRow).join('') || '<span class="task-meta">No tasks today.</span>'; $('#daily-study').innerHTML = data.daily_study_minutes.map(day => `<div class="bar-wrap"><div class="bar" style="height:${Math.min(150, Math.max(3, day.minutes * 2))}px"></div><div class="bar-label">${day.date.slice(5)}</div></div>`).join(''); } catch (error) { flash(error.message); } }
async function loadCourses() { try { state.courses = await api('/courses'); $('#course-list').innerHTML = state.courses.map(course => `<article class="course-card"><h4>${escapeHtml(course.name)}</h4><p>${escapeHtml(course.subject || 'Other')}</p><p>${escapeHtml(course.description || 'No description')}</p></article>`).join('') || '<span class="task-meta">No courses yet.</span>'; } catch (error) { flash(error.message); } }
async function loadTasks() { try { await ensureCourses(); $('#task-course').innerHTML = courseOptions(); const tasks = await api('/tasks'); $('#task-list').innerHTML = tasks.map(taskRow).join('') || '<span class="task-meta">No tasks yet.</span>'; document.querySelectorAll('[data-complete]').forEach(button => button.onclick = async () => { try { await api(`/tasks/${button.dataset.complete}/complete`, { method: 'POST' }); flash('Task completed'); loadTasks(); } catch (error) { flash(error.message); } }); } catch (error) { flash(error.message); } }
async function loadGoals() { try { await ensureCourses(); $('#goal-course').innerHTML = courseOptions(); $('#knowledge-course').innerHTML = courseOptions('Select course'); const [goals, points] = await Promise.all([api('/goals'), api('/knowledge-points')]); const courseName = id => escapeHtml(state.courses.find(course => course.id === id)?.name || 'No course'); $('#goal-list').innerHTML = goals.map(goal => `<article class="list-row"><div><strong>${escapeHtml(goal.title)}</strong><div class="task-meta">Due ${goal.target_date} · ${goal.weekly_minutes} min/week${goal.target_score === null ? '' : ` · score ${goal.target_score}`}</div></div><span class="task-meta">${escapeHtml(goal.status)} · ${goal.progress}%</span></article>`).join('') || '<span class="task-meta">No goals yet.</span>'; $('#knowledge-point-list').innerHTML = points.map(point => `<article class="list-row"><div><strong>${escapeHtml(point.name)}</strong><div class="task-meta">${courseName(point.course_id)} · ${escapeHtml(point.category)} · difficulty ${point.difficulty}/5</div></div><span class="task-meta">Mastery ${point.mastery}% · importance ${point.importance}/5</span></article>`).join('') || '<span class="task-meta">No knowledge points yet.</span>'; } catch (error) { flash(error.message); } }
async function loadPractice() { try { await ensureCourses(); $('#question-course').innerHTML = courseOptions(); state.questions = await api('/questions'); $('#question-list').innerHTML = state.questions.map(question => { const options = String(question.options || '').split('\\n').map(item => item.trim()).filter(Boolean); return `<label class="list-row question-row"><input type="checkbox" data-question-select="${question.id}"><div class="question-copy"><strong class="math-text">${mathHtml(question.prompt)}</strong>${options.length ? `<div class="question-options">${options.map(option => `<span class="math-text">${mathHtml(option)}</span>`).join('')}</div>` : ''}<div class="task-meta">${escapeHtml(question.kind)} · difficulty ${question.difficulty}</div></div></label>`; }).join('') || '<span class="task-meta">Add questions to start practice.</span>'; typesetMath($('#question-list')); const reviews = await api('/reviews?due_only=true'); $('#review-list').innerHTML = reviews.map(review => `<article class="list-row"><div><strong class="math-text">${mathHtml(review.title)}</strong><div class="task-meta">Wrong ${review.wrong_count} · ${review.next_review}</div></div><select data-review="${review.id}"><option value="correct">Mastered</option><option value="wrong">Not yet</option><option value="postpone">Tomorrow</option></select></article>`).join('') || '<span class="task-meta">No due reviews.</span>'; typesetMath($('#review-list')); document.querySelectorAll('[data-review]').forEach(select => select.onchange = async () => { try { await api(`/reviews/${select.dataset.review}/attempts`, { method: 'POST', body: JSON.stringify({ result: select.value }) }); flash('Review recorded'); loadPractice(); } catch (error) { flash(error.message); } }); renderPracticeRun(); } catch (error) { flash(error.message); } }
async function loadResources() { try { await ensureCourses(); $('#resource-course').innerHTML = courseOptions(); $('#rag-course').innerHTML = courseOptions('All courses'); const resources = await api('/resources'); $('#resource-list').innerHTML = resources.map(resource => `<article class="list-row"><div><strong>${escapeHtml(resource.name)}</strong><div class="task-meta">${Math.ceil(resource.size / 1024)} KB · ${resource.course_id ? `Course #${resource.course_id}` : 'No course'}</div></div></article>`).join('') || '<span class="task-meta">No resources yet.</span>'; } catch (error) { flash(error.message); } }
async function downloadAgentReport(url) { const response = await fetch(url, { headers: { Authorization: `Bearer ${state.token}` } }); if (!response.ok) throw new Error('Download failed'); const blob = await response.blob(); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'learning-report.md'; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(link.href); }
function bindAgentDownloads(root) { root.querySelectorAll('[data-download-url]').forEach(link => link.onclick = async event => { event.preventDefault(); try { await downloadAgentReport(link.dataset.downloadUrl); } catch (error) { flash(error.message); } }); }
function renderRichBlocks(blocks, messageId = '') { return (blocks || []).map((block, index) => {
  if (block.type !== 'quiz') return `<div class="rich-markdown">${escapeHtml(block.content || '').replace(/\n/g, '<br>')}</div>`;
  const questions = Array.isArray(block.questions) ? block.questions : [];
  const quizId = `quiz-${messageId || Date.now()}-${index}`;
  return `<section class="rich-quiz" data-quiz="${quizId}"><div class="rich-quiz-head"><strong>Interactive practice</strong><span class="quiz-progress">0 / ${questions.length}</span></div>${questions.map((question, qIndex) => `<fieldset class="rich-question" data-q-index="${qIndex}"><legend>${qIndex + 1}. ${escapeHtml(question.prompt || '')}</legend><div class="rich-options">${(question.options || []).map(option => `<label class="rich-option"><input type="radio" name="${quizId}-${qIndex}" value="${escapeHtml(option.id || option.label || '')}"><span><b>${escapeHtml(option.id || '')}</b> ${escapeHtml(option.label || '')}</span></label>`).join('')}</div></fieldset>`).join('')}<div class="rich-quiz-actions"><button type="button" class="primary rich-finish">完成</button><button type="button" class="secondary rich-submit hidden">提交给 AI</button></div></section>`;
}).join(''); }
function bindRichQuizzes(root) { root.querySelectorAll('.rich-quiz').forEach(quiz => { if (quiz.dataset.bound) return; quiz.dataset.bound = '1'; const total = quiz.querySelectorAll('.rich-question').length; const progress = quiz.querySelector('.quiz-progress'); const update = () => { const done = [...quiz.querySelectorAll('.rich-question')].filter(q => q.querySelector('input:checked')).length; progress.textContent = `${done} / ${total}`; quiz.querySelector('.rich-finish').disabled = done < total; }; quiz.addEventListener('change', update); quiz.querySelector('.rich-finish').onclick = () => { quiz.classList.add('rich-review'); quiz.querySelector('.rich-finish').classList.add('hidden'); quiz.querySelector('.rich-submit').classList.remove('hidden'); }; quiz.querySelector('.rich-submit').onclick = async () => { const answers = [...quiz.querySelectorAll('.rich-question')].map((q, index) => ({ question_index: index + 1, answer: q.querySelector('input:checked')?.value || '' })); quiz.querySelector('.rich-submit').disabled = true; quiz.insertAdjacentHTML('beforeend', '<p class="task-meta rich-submit-status">已提交，Agent 正在批改并更新学习记录...</p>'); try { await sendAgentEvent('exercise_submission', { quiz_id: quiz.dataset.quiz, answers }); quiz.querySelector('.rich-submit-status').textContent = '已提交给 AI，会话中将继续给出解析。'; } catch (error) { quiz.querySelector('.rich-submit-status').textContent = `提交失败：${error.message}`; quiz.querySelector('.rich-submit').disabled = false; } }; update(); }); }
function renderAgentMessageContent(message) { const blocks = Array.isArray(message.blocks) ? message.blocks : [{ type: 'markdown', content: message.content }]; return renderRichBlocks(blocks, message.id); }
function renderAgentMessages(messages) { const root = $('#agent-messages'); root.innerHTML = messages.map(message => `<article class="agent-message ${escapeHtml(message.role)}"><strong>${message.role === 'user' ? 'You' : 'Learning Agent'}</strong><div>${renderAgentMessageContent(message)}</div></article>`).join('') || '<p class="task-meta">Start a conversation with your learning agent.</p>'; bindAgentDownloads(root); bindRichQuizzes(root); root.scrollTop = root.scrollHeight; }
async function sendAgentEvent(eventType, payload) { if (!state.agentSessionId) throw new Error('No active Agent conversation'); const response = await fetch(`/v1/agent/sessions/${normalizeAgentSessionId(state.agentSessionId)}/messages/stream`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${state.token}` }, body: JSON.stringify({ message: 'Exercise submission', event_type: eventType, event_payload: payload }) }); if (!response.ok) throw new Error('Agent submission failed'); const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = '', answer = ''; while (true) { const part = await reader.read(); if (part.done) break; buffer += decoder.decode(part.value, { stream: true }); const events = buffer.split('\n\n'); buffer = events.pop(); for (const event of events) { const name = event.match(/^event: (.+)$/m)?.[1]; const raw = event.match(/^data: (.+)$/m)?.[1]; if (!raw) continue; const data = JSON.parse(raw); if (name === 'token') answer += data.text || ''; } } if (answer) { const root = $('#agent-messages'); root.insertAdjacentHTML('beforeend', `<article class="agent-message assistant"><strong>Learning Agent</strong><div>${escapeHtml(answer).replace(/\n/g, '<br>')}</div></article>`); root.scrollTop = root.scrollHeight; } }
function renderAgentSessions() { $('#agent-session-list').innerHTML = state.agentSessions.map(item => `<button class="session-row ${item.id === state.agentSessionId ? 'active' : ''}" data-agent-session="${item.id}">${escapeHtml(item.title)}</button>`).join('') || '<p class="task-meta">No conversations.</p>'; document.querySelectorAll('[data-agent-session]').forEach(button => button.onclick = () => selectAgentSession(Number(button.dataset.agentSession))); }
function normalizeAgentSessionId(value) { const id = typeof value === 'object' && value !== null ? value.id : value; const numeric = Number(id); if (!Number.isInteger(numeric) || numeric < 1) throw new Error('Invalid agent conversation. Create a new conversation and try again.'); return numeric; }
async function selectAgentSession(sessionId) { try { const id = normalizeAgentSessionId(sessionId); state.agentSessionId = id; localStorage.setItem('learning_agent_session_id', String(id)); renderAgentSessions(); renderAgentMessages(await api(`/agent/sessions/${id}/messages`)); } catch (error) { flash(error.message); renderAgentMessages([{ role: 'assistant', content: `Unable to open this conversation: ${error.message}` }]); } }
async function createAgentSession() { const session = await api('/agent/sessions', { method: 'POST', body: JSON.stringify({ title: 'New session' }) }); state.agentSessions = [session, ...state.agentSessions]; await selectAgentSession(session); }
async function loadAiCenter() { try { await ensureCourses(); state.agentSessions = await api('/agent/sessions'); renderAgentSessions(); if (state.agentSessionId && state.agentSessions.some(item => item.id === state.agentSessionId)) await selectAgentSession(state.agentSessionId); else if (state.agentSessions[0]) await selectAgentSession(state.agentSessions[0]); } catch (error) { flash(error.message); } }
async function loadMembers() { try { const canManage = ['owner', 'admin'].includes(state.user.role); $('#new-member').classList.toggle('hidden', !canManage); const members = await api('/organization/members'); $('#member-list').innerHTML = members.map(member => { const editable = canManage && member.role !== 'owner' && member.user_id !== state.user.id; const control = editable ? `<div class="member-actions"><select data-member-role="${member.user_id}"><option value="member" ${member.role === 'member' ? 'selected' : ''}>Member</option><option value="admin" ${member.role === 'admin' ? 'selected' : ''}>Admin</option></select><button class="secondary" data-member-remove="${member.user_id}">Remove</button></div>` : `<span class="task-meta">${member.user_id === state.user.id ? 'Current user' : ''}</span>`; return `<article class="list-row"><div><strong>${escapeHtml(member.display_name || member.email)}</strong><div class="task-meta">${escapeHtml(member.email)} · ${escapeHtml(member.role)}</div></div>${control}</article>`; }).join('') || '<span class="task-meta">No members.</span>'; document.querySelectorAll('[data-member-role]').forEach(select => select.onchange = async () => { try { await api(`/organization/members/${select.dataset.memberRole}`, { method: 'PATCH', body: JSON.stringify({ role: select.value }) }); flash('Role updated'); loadMembers(); } catch (error) { flash(error.message); } }); document.querySelectorAll('[data-member-remove]').forEach(button => button.onclick = async () => { if (!confirm('Remove this member?')) return; try { await api(`/organization/members/${button.dataset.memberRemove}`, { method: 'DELETE' }); flash('Member removed'); loadMembers(); } catch (error) { flash(error.message); } }); } catch (error) { flash(error.message); } }
function renderPracticeRun() { const root = $('#practice-run'); if (!state.practice) { root.innerHTML = '<p class="task-meta">Select questions to begin.</p>'; return; } const current = state.practice.questions[state.practice.index]; if (!current) return; const options = String(current.options || '').split('\\n').map(item => item.trim()).filter(Boolean); root.innerHTML = `<p class="task-meta">${state.practice.index + 1} / ${state.practice.questions.length}</p><p class="practice-prompt math-text">${mathHtml(current.prompt)}</p>${options.length ? `<div class="practice-options">${options.map(option => `<label><input type="radio" name="choice" value="${escapeHtml(option)}"><span class="math-text">${mathHtml(option)}</span></label>`).join('')}</div>` : ''}<form id="practice-answer-form" class="practice-answer"><input name="response" autocomplete="off" placeholder="Answer" ${options.length ? '' : 'required'}><button class="primary">Submit</button></form>`; typesetMath(root); $('#practice-answer-form').onsubmit = async event => { event.preventDefault(); try { const formData = new FormData(event.target); const selected = root.querySelector('[name="choice"]:checked'); const response = selected ? selected.value : formData.get('response'); if (!response) { flash('Select an option or enter an answer.'); return; } const result = await api(`/practice-sessions/${state.practice.id}/questions/${current.id}/attempts`, { method: 'POST', body: JSON.stringify({ response, elapsed_seconds: 0 }) }); root.insertAdjacentHTML('beforeend', `<div class="practice-feedback ${result.correct ? 'correct' : 'incorrect'}"><strong>${result.correct ? 'Correct' : 'Recorded'}</strong>${current.explanation ? `<p class="math-text">${mathHtml(current.explanation)}</p>` : ''}<button type="button" class="secondary" id="next-practice">${state.practice.index + 1 >= state.practice.questions.length ? 'Finish' : 'Next question'}</button></div>`); typesetMath(root); event.target.querySelector('button').disabled = true; $('#next-practice').onclick = async () => { state.practice.index += 1; if (state.practice.index >= state.practice.questions.length) { const summary = await api(`/practice-sessions/${state.practice.id}/complete`, { method: 'POST' }); flash(`完成：${summary.correct}/${summary.total}，准确率 ${summary.accuracy}%`); if (summary.analysis_job_id) watchPracticeAnalysis(summary.analysis_job_id); state.practice = null; await loadPractice(); } else renderPracticeRun(); }; } catch (error) { flash(error.message); } }; }
async function watchJob(jobId, label) { const root = $('#rag-job'); for (let count = 0; count < 60; count += 1) { const job = await api(`/jobs/${jobId}`); root.innerHTML = `<strong>${escapeHtml(label)}</strong><p class="task-meta">Status: ${escapeHtml(job.status)}${job.detail ? ` · ${escapeHtml(job.detail)}` : ''}${job.error ? ` · ${escapeHtml(job.error)}` : ''}</p>`; if (job.status === 'completed') { const result = job.result || {}; if (result.ai_run_id) { const run = await api(`/ai-runs/${result.ai_run_id}`); const citations = (run.citations || []).map(citation => `<article class="citation"><strong>[${citation.number}]</strong> ${escapeHtml(citation.quote_text)}</article>`).join('') || '<p class="task-meta">No evidence found.</p>'; root.innerHTML = result.mode === 'generated' && result.answer ? `<strong>Answer</strong><p class="answer-text">${escapeHtml(result.answer)}</p><div class="citation-list">${citations}</div>` : `<strong>${escapeHtml(label)}</strong><p class="task-meta">Evidence search complete: ${result.evidence_count || 0} result(s). Configure an LLM to generate an answer.</p><div class="citation-list">${citations}</div>`; } return; } if (job.status === 'failed') return; await new Promise(resolve => setTimeout(resolve, 2000)); } root.innerHTML = `<strong>${escapeHtml(label)}</strong><p class="task-meta">Still processing. Refresh later.</p>`; }
async function watchGenerationJob(jobId) { const root = $('#generation-job'); for (let count = 0; count < 60; count += 1) { const job = await api(`/jobs/${jobId}`); root.innerHTML = `<strong>AI question generation</strong><p class="task-meta">Status: ${escapeHtml(job.status)}${job.detail ? ` · ${escapeHtml(job.detail)}` : ''}${job.error ? ` · ${escapeHtml(job.error)}` : ''}</p>`; if (job.status === 'completed') { const result = job.result || {}; root.innerHTML = `<strong>AI question generation</strong><p class="task-meta">Created ${Number(result.count || 0)} question(s) from ${Number(result.evidence_count || 0)} evidence chunk(s).</p>`; await loadPractice(); return; } if (job.status === 'failed') return; await new Promise(resolve => setTimeout(resolve, 2000)); } root.innerHTML = '<p class="task-meta">Still processing. Refresh later.</p>'; }
async function watchPracticeAnalysis(jobId) { const root = $('#practice-run'); for (let count = 0; count < 60; count += 1) { const job = await api(`/jobs/${jobId}`); if (job.status === 'completed') { const output = job.result?.output || {}; root.insertAdjacentHTML('beforeend', `<div class="practice-feedback"><strong>AI 学习分析已完成</strong><p>${escapeHtml(output.summary || output.answer || '已根据本次练习更新下一步建议。')}</p>${Array.isArray(output.recommendations) ? `<ul>${output.recommendations.map(item => `<li>${escapeHtml(item)}</li>`).join('')}</ul>` : ''}</div>`); window.dispatchEvent(new CustomEvent('learning-data-updated', { detail: job.result })); if (job.result?.next_plan_job_id) watchAdaptivePlan(job.result.next_plan_job_id); return; } if (job.status === 'failed') { root.insertAdjacentHTML('beforeend', `<p class="error-text">学习分析失败：${escapeHtml(job.error || job.detail || '')}</p>`); return; } await new Promise(resolve => setTimeout(resolve, 2000)); } }
async function watchAdaptivePlan(jobId) { const root = $('#practice-run'); for (let count = 0; count < 60; count += 1) { const job = await api(`/jobs/${jobId}`); if (job.status === 'completed') { const count = Number(job.result?.created_task_count || 0); root.insertAdjacentHTML('beforeend', `<p class="task-meta">下一轮复习计划已写入 ${count} 个任务。</p>`); window.dispatchEvent(new CustomEvent('learning-data-updated', { detail: job.result })); return; } if (job.status === 'failed') return; await new Promise(resolve => setTimeout(resolve, 2000)); } }

$('#new-course').onclick = () => $('#course-form').classList.remove('hidden');
$('#new-task').onclick = () => { $('#task-form').classList.remove('hidden'); $('#task-form [name=planned_date]').value = new Date().toISOString().slice(0, 10); };
$('#new-goal').onclick = () => { $('#goal-form').classList.remove('hidden'); $('#goal-form [name=target_date]').value = new Date().toISOString().slice(0, 10); };
$('#new-knowledge-point').onclick = () => $('#knowledge-point-form').classList.remove('hidden');
$('#new-question').onclick = () => $('#question-form').classList.remove('hidden');
$('#new-vocabulary').onclick = () => $('#vocabulary-form').classList.remove('hidden');
$('#generate-questions').onclick = () => { $('#generation-course').innerHTML = courseOptions('Select course'); $('#question-generation-form').classList.remove('hidden'); };
$('#new-member').onclick = () => $('#member-form').classList.remove('hidden');
$('#new-agent-session').onclick = async () => { try { await createAgentSession(); } catch (error) { flash(error.message); } };
$('#refresh-resources').onclick = loadResources;
document.querySelectorAll('[data-close-form]').forEach(button => button.onclick = () => $(`#${button.dataset.closeForm}`).classList.add('hidden'));
$('#course-form').onsubmit = async event => { event.preventDefault(); try { await api('/courses', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.target))) }); event.target.reset(); event.target.classList.add('hidden'); state.courses = []; flash('Course created'); loadCourses(); } catch (error) { flash(error.message); } };
$('#task-form').onsubmit = async event => { event.preventDefault(); try { const data = Object.fromEntries(new FormData(event.target)); data.duration_minutes = Number(data.duration_minutes); data.course_id = data.course_id ? Number(data.course_id) : null; await api('/tasks', { method: 'POST', body: JSON.stringify(data) }); event.target.classList.add('hidden'); flash('Task created'); loadTasks(); } catch (error) { flash(error.message); } };
setInterval(async () => { if (!state.token) return; try { const tasks = await api('/tasks?start=' + new Date().toISOString().slice(0, 10) + '&end=' + new Date().toISOString().slice(0, 10)); const now = new Date(); const key = `${now.toISOString().slice(0, 10)} ${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`; const task = tasks.find(item => !item.completed && item.scheduled_time && `${item.planned_date} ${item.scheduled_time}` === key); const noticeKey = task && `study-notice:${task.id}:${key}`; if (task && noticeKey && !localStorage.getItem(noticeKey) && 'Notification' in window) { localStorage.setItem(noticeKey, '1'); if (Notification.permission === 'default') await Notification.requestPermission(); if (Notification.permission === 'granted') new Notification('学习提醒', { body: task.title }); } } catch (_) {} }, 60000);
$('#goal-form').onsubmit = async event => { event.preventDefault(); try { const data = Object.fromEntries(new FormData(event.target)); data.weekly_minutes = Number(data.weekly_minutes); data.target_score = data.target_score ? Number(data.target_score) : null; data.course_id = data.course_id ? Number(data.course_id) : null; await api('/goals', { method: 'POST', body: JSON.stringify(data) }); event.target.reset(); event.target.classList.add('hidden'); flash('Goal created'); loadGoals(); } catch (error) { flash(error.message); } };
$('#knowledge-point-form').onsubmit = async event => { event.preventDefault(); try { const data = Object.fromEntries(new FormData(event.target)); data.course_id = Number(data.course_id); data.difficulty = Number(data.difficulty); data.importance = Number(data.importance); await api('/knowledge-points', { method: 'POST', body: JSON.stringify(data) }); event.target.reset(); event.target.classList.add('hidden'); flash('Knowledge point created'); loadGoals(); } catch (error) { flash(error.message); } };
$('#question-form').onsubmit = async event => { event.preventDefault(); try { const data = Object.fromEntries(new FormData(event.target)); data.course_id = data.course_id ? Number(data.course_id) : null; data.difficulty = Number(data.difficulty); await api('/questions', { method: 'POST', body: JSON.stringify(data) }); event.target.reset(); event.target.classList.add('hidden'); flash('Question saved'); loadPractice(); } catch (error) { flash(error.message); } };
$('#vocabulary-form').onsubmit = async event => { event.preventDefault(); try { await api('/vocabulary', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.target))) }); event.target.reset(); event.target.classList.add('hidden'); flash('Word added to spaced review'); loadVocabulary(); } catch (error) { flash(error.message); } };
$('#question-generation-form').onsubmit = async event => { event.preventDefault(); try { const data = Object.fromEntries(new FormData(event.target)); data.course_id = Number(data.course_id); data.count = Number(data.count); data.difficulty = Number(data.difficulty); data.kinds = data.kinds === 'mixed' ? ['single_choice', 'short_answer'] : [data.kinds]; const result = await api('/ai/question-generation/jobs', { method: 'POST', body: JSON.stringify(data) }); event.target.classList.add('hidden'); flash('AI question generation submitted'); watchGenerationJob(result.job_id); } catch (error) { flash(error.message); } };
$('#start-practice').onclick = async () => { const ids = [...document.querySelectorAll('[data-question-select]:checked')].map(item => Number(item.dataset.questionSelect)); if (!ids.length) return flash('Select at least one question'); try { const session = await api('/practice-sessions', { method: 'POST', body: JSON.stringify({ question_ids: ids }) }); state.practice = { id: session.id, questions: state.questions.filter(question => ids.includes(question.id)), index: 0 }; renderPracticeRun(); flash('Practice started'); } catch (error) { flash(error.message); } };
$('#resource-form').onsubmit = async event => { event.preventDefault(); try { const data = new FormData(event.target); if (!data.get('course_id')) data.delete('course_id'); const result = await api('/resources', { method: 'POST', body: data }); flash('Resource uploaded; indexing started'); event.target.reset(); watchJob(result.job_id, 'Resource indexing'); loadResources(); } catch (error) { flash(error.message); } };
$('#rag-form').onsubmit = async event => { event.preventDefault(); try { const data = Object.fromEntries(new FormData(event.target)); data.course_id = data.course_id ? Number(data.course_id) : null; const result = await api('/rag/jobs', { method: 'POST', body: JSON.stringify(data) }); flash('Evidence search submitted'); watchJob(result.job_id, 'Evidence search'); } catch (error) { flash(error.message); } };
$('#agent-form').onsubmit = async event => { event.preventDefault(); let pending = null; try { if (!state.agentSessionId) await createAgentSession(); const data = Object.fromEntries(new FormData(event.target)); data.course_id = data.course_id ? Number(data.course_id) : null; const root = $('#agent-messages'); const user = data.message.trim(); root.insertAdjacentHTML('beforeend', `<article class="agent-message user"><strong>You</strong><div>${escapeHtml(user)}</div></article><article class="agent-message assistant thinking"><strong>Learning Agent</strong><div>Thinking...</div></article>`); pending = root.querySelector('.thinking'); root.scrollTop = root.scrollHeight; event.target.querySelector('[name=message]').value = ''; const sessionId = normalizeAgentSessionId(state.agentSessionId); const response = await fetch(`/v1/agent/sessions/${sessionId}/messages/stream`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${state.token}` }, body: JSON.stringify(data) }); if (!response.ok || !response.body) { const body = await response.json().catch(() => ({})); throw new Error(body.detail || `Agent request failed (${response.status})`); } const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = '', answer = '', thinking = pending; while (true) { const part = await reader.read(); if (part.done) break; buffer += decoder.decode(part.value, { stream: true }); const events = buffer.split('\n\n'); buffer = events.pop(); for (const event of events) { const name = event.match(/^event: (.+)$/m)?.[1]; const raw = event.match(/^data: (.+)$/m)?.[1]; if (!raw) continue; const payload = JSON.parse(raw); if (name === 'token') { answer += payload.text; if (thinking) { thinking.classList.remove('thinking'); thinking.querySelector('div').textContent = answer; } } if (name === 'intent' && thinking) thinking.querySelector('div').textContent = `Understanding intent: ${(payload.actions || []).join(', ')}...`; if (name === 'done') { state.agentSessions = await api('/agent/sessions'); renderAgentSessions(); } } } } catch (error) { const message = `Error: ${error.message}`; flash(message); if (pending) { pending.classList.remove('thinking'); pending.classList.add('error'); pending.querySelector('div').textContent = message; } } };
$('#member-form').onsubmit = async event => { event.preventDefault(); try { await api('/organization/members', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.target))) }); event.target.reset(); event.target.classList.add('hidden'); flash('Member added'); loadMembers(); } catch (error) { flash(error.message); } };
$('#logout').onclick = async () => { try { if (state.refreshToken) await fetch('/v1/auth/logout', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ refresh_token: state.refreshToken }) }); } finally { showAuth(); } };
if (state.token) api('/me').then(user => { state.user = user; showApp(); }).catch(showAuth);
window.addEventListener('learning-data-updated', () => {
  const view = document.querySelector('.sidebar .nav-item.active')?.dataset.view;
  if (view) void loadCurrentView(view);
  void loadDashboard();
});
window.addEventListener('practice-ready', async event => {
  const result = event.detail || {};
  if (!result.practice_session_id || !Array.isArray(result.question_ids)) return;
  try {
    state.questions = await api('/questions');
    const questions = state.questions.filter(item => result.question_ids.includes(item.id));
    state.practice = { id: result.practice_session_id, questions, index: 0 };
    openView('practice');
    renderPracticeRun();
    flash('题目已生成，练习已自动开始');
  } catch (error) { flash(`无法打开自动练习：${error.message}`); }
});
function appendStreamDownload(target, payload) { if (!target || !payload?.url) return; const link = document.createElement('a'); link.className = 'download-link'; link.href = payload.url; link.textContent = payload.label || 'Download report'; link.onclick = async event => { event.preventDefault(); try { await downloadAgentReport(payload.url); } catch (error) { flash(error.message); } }; target.appendChild(document.createElement('br')); target.appendChild(link); }
const agentDownloadObserver = new MutationObserver(() => { const root = $('#agent-messages'); if (!root) return; root.querySelectorAll('.agent-message div').forEach(node => { if (node.dataset.downloadBound) return; const match = node.textContent.match(/(\/v1\/agent\/sessions\/\d+\/downloads\/\d+)/); if (!match) return; node.dataset.downloadBound = '1'; node.innerHTML = escapeHtml(node.textContent.replace(match[1], '')).replace(/\n/g, '<br>') + `<br><a class="download-link" href="${match[1]}" data-download-url="${match[1]}">Download report</a>`; bindAgentDownloads(root); }); });
agentDownloadObserver.observe(document.body, { subtree: true, childList: true, characterData: true });
function parseRichTextClient(text) { const source = String(text || ''); const re = /(?:^|\n)\s*(\d+)\.\s+([^\n]+)\n((?:\s*[A-H][\.)]\s+[^\n]+\n?)+)/g; const questions = []; let match; while ((match = re.exec(source))) { const options = [...match[3].matchAll(/^\s*([A-H])[\.)]\s+(.+?)\s*$/gm)].map(item => ({ id: item[1], label: item[2] })); if (options.length) questions.push({ number: Number(match[1]), prompt: match[2], options }); } return questions.length ? [{ type: 'markdown', content: source.slice(0, source.indexOf(`${questions[0].number}.`)).trim() }, { type: 'quiz', questions }] : null; }
const richStreamObserver = new MutationObserver(() => { document.querySelectorAll('.agent-message.assistant:not([data-rich-bound])').forEach(node => { const body = node.querySelector('div'); if (!body || node.classList.contains('thinking')) return; const parsed = parseRichTextClient(body.textContent); if (!parsed) return; node.dataset.richBound = '1'; body.innerHTML = renderRichBlocks(parsed); bindRichQuizzes(node); }); });
richStreamObserver.observe(document.body, { subtree: true, childList: true, characterData: true });
