"""add ai document and draft tables

Revision ID: 7d23839ea774
Revises: b969fe52eef5
Create Date: 2026-07-27 16:21:17.518562
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '7d23839ea774'
down_revision: Union[str, None] = 'b969fe52eef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_uuid', sa.String(length=36), nullable=False),
    sa.Column('feature', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=160), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_runs_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_runs_feature'), ['feature'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_runs_run_uuid'), ['run_uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_ai_runs_status'), ['status'], unique=False)

    op.create_table('document_indexes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parser_version', sa.String(length=40), nullable=False),
    sa.Column('chunker_version', sa.String(length=40), nullable=False),
    sa.Column('embedding_model', sa.String(length=160), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'parser_version', 'chunker_version', 'embedding_model', name='uq_document_index_version')
    )
    with op.batch_alter_table('document_indexes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_indexes_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_indexes_source_sha256'), ['source_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_indexes_status'), ['status'], unique=False)

    op.create_table('knowledge_point_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_run_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('prerequisites_json', sa.Text(), nullable=False),
    sa.Column('related_points_json', sa.Text(), nullable=False),
    sa.Column('common_mistakes_json', sa.Text(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=False),
    sa.Column('accepted_knowledge_point_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_knowledge_point_id'], ['knowledge_points.id'], ),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai_runs.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_point_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_point_drafts_ai_run_id'), ['ai_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_point_drafts_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_point_drafts_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_point_drafts_status'), ['status'], unique=False)

    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_index_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('chunk_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('section_title', sa.String(length=500), nullable=False),
    sa.Column('location_label', sa.String(length=300), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('vector_id', sa.String(length=100), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['document_index_id'], ['document_indexes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_index_id', 'chunk_number', name='uq_document_chunk_number'),
    sa.UniqueConstraint('vector_id')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunks_content_sha256'), ['content_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_document_index_id'), ['document_index_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_resource_id'), ['resource_id'], unique=False)

    op.create_table('question_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_run_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=False),
    sa.Column('accepted_question_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai_runs.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_drafts_ai_run_id'), ['ai_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_drafts_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_drafts_knowledge_point_id'), ['knowledge_point_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_drafts_status'), ['status'], unique=False)

    op.create_table('ai_citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_run_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('citation_number', sa.Integer(), nullable=False),
    sa.Column('quote_text', sa.Text(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ai_run_id', 'chunk_id', 'citation_number', name='uq_ai_citation_position')
    )
    with op.batch_alter_table('ai_citations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_citations_ai_run_id'), ['ai_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_citations_chunk_id'), ['chunk_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_citations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_citations_chunk_id'))
        batch_op.drop_index(batch_op.f('ix_ai_citations_ai_run_id'))

    op.drop_table('ai_citations')
    with op.batch_alter_table('question_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_drafts_status'))
        batch_op.drop_index(batch_op.f('ix_question_drafts_knowledge_point_id'))
        batch_op.drop_index(batch_op.f('ix_question_drafts_course_id'))
        batch_op.drop_index(batch_op.f('ix_question_drafts_ai_run_id'))

    op.drop_table('question_drafts')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_resource_id'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_document_index_id'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_course_id'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_content_sha256'))

    op.drop_table('document_chunks')
    with op.batch_alter_table('knowledge_point_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_point_drafts_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_point_drafts_name'))
        batch_op.drop_index(batch_op.f('ix_knowledge_point_drafts_course_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_point_drafts_ai_run_id'))

    op.drop_table('knowledge_point_drafts')
    with op.batch_alter_table('document_indexes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_indexes_status'))
        batch_op.drop_index(batch_op.f('ix_document_indexes_source_sha256'))
        batch_op.drop_index(batch_op.f('ix_document_indexes_resource_id'))

    op.drop_table('document_indexes')
    with op.batch_alter_table('ai_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_runs_status'))
        batch_op.drop_index(batch_op.f('ix_ai_runs_run_uuid'))
        batch_op.drop_index(batch_op.f('ix_ai_runs_feature'))
        batch_op.drop_index(batch_op.f('ix_ai_runs_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_runs_course_id'))

    op.drop_table('ai_runs')
    # ### end Alembic commands ###
