"""initial schema

Revision ID: b969fe52eef5
Revises: 
Create Date: 2026-07-25 19:24:31.865652
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'b969fe52eef5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('background_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_status'), ['status'], unique=False)

    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('education_stage', sa.String(length=40), nullable=False),
    sa.Column('grade_level', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.String(length=60), nullable=False),
    sa.Column('exam_type', sa.String(length=60), nullable=False),
    sa.Column('textbook_version', sa.String(length=80), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('target_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('color_tag', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_opened_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_status'), ['status'], unique=False)

    op.create_table('tool_call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=120), nullable=False),
    sa.Column('arguments', sa.Text(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id')
    )
    with op.batch_alter_table('tool_call_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_call_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_call_logs_tool_name'), ['tool_name'], unique=False)

    op.create_table('knowledge_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('mastery', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_points_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_points_name'), ['name'], unique=False)

    op.create_table('practice_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_sessions_started_at'), ['started_at'], unique=False)

    op.create_table('resource_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('source_path', sa.String(length=1000), nullable=False),
    sa.Column('relative_path', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=False),
    sa.Column('trashed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relative_path')
    )
    with op.batch_alter_table('resource_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_files_sha256'), ['sha256'], unique=False)

    op.create_table('study_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('target_score', sa.Float(), nullable=True),
    sa.Column('weekly_minutes', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_goals_target_date'), ['target_date'], unique=False)

    op.create_table('study_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.String(length=30), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('scheduled_time', sa.String(length=5), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('recurrence_key', sa.String(length=80), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_tasks_planned_date'), ['planned_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_tasks_title'), ['title'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=300), nullable=False),
    sa.Column('options', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['study_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_sessions_started_at'), ['started_at'], unique=False)

    op.create_table('task_recurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['study_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('practice_session_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('marked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['practice_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_session_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_session_questions_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_session_questions_session_id'), ['session_id'], unique=False)

    op.create_table('question_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('elapsed_seconds', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['practice_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_attempts_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_attempts_session_id'), ['session_id'], unique=False)

    op.create_table('review_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('next_review', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('error_reason', sa.String(length=300), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_items_next_review'), ['next_review'], unique=False)

    op.create_table('review_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_item_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('previous_streak', sa.Integer(), nullable=False),
    sa.Column('next_review', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['review_item_id'], ['review_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_attempts_review_item_id'), ['review_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_attempts_review_item_id'))

    op.drop_table('review_attempts')
    with op.batch_alter_table('review_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_items_next_review'))

    op.drop_table('review_items')
    with op.batch_alter_table('question_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_attempts_session_id'))
        batch_op.drop_index(batch_op.f('ix_question_attempts_question_id'))

    op.drop_table('question_attempts')
    with op.batch_alter_table('practice_session_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_session_questions_session_id'))
        batch_op.drop_index(batch_op.f('ix_practice_session_questions_question_id'))

    op.drop_table('practice_session_questions')
    op.drop_table('task_recurrences')
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_sessions_started_at'))

    op.drop_table('study_sessions')
    op.drop_table('questions')
    with op.batch_alter_table('study_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_tasks_title'))
        batch_op.drop_index(batch_op.f('ix_study_tasks_planned_date'))

    op.drop_table('study_tasks')
    with op.batch_alter_table('study_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_goals_target_date'))

    op.drop_table('study_goals')
    with op.batch_alter_table('resource_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_files_sha256'))

    op.drop_table('resource_files')
    with op.batch_alter_table('practice_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_sessions_started_at'))

    op.drop_table('practice_sessions')
    with op.batch_alter_table('knowledge_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_points_name'))
        batch_op.drop_index(batch_op.f('ix_knowledge_points_course_id'))

    op.drop_table('knowledge_points')
    with op.batch_alter_table('tool_call_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_call_logs_tool_name'))
        batch_op.drop_index(batch_op.f('ix_tool_call_logs_created_at'))

    op.drop_table('tool_call_logs')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_status'))
        batch_op.drop_index(batch_op.f('ix_courses_name'))

    op.drop_table('courses')
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_job_type'))

    op.drop_table('background_jobs')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
